package com.example.mom.mom.Model;

/**
 * Created by jesse on 2/29/16.
 */
public enum Major {
    NO_MAJOR,
    ARCHITECTURE,
    BUILDING_CONSTRUCTION,
    INDUSTRIAL_DESIGN,
    COMPUTER_SCIENCE,
    COMPUTATIONAL_MEDIA,
    AEROSPACE_ENGINEERING,
    BIOMEDICAL_ENGINEERING,
    CHEMICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    COMPUTER_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    INDUSTRIAL_ENGINEERING,
    MATERIAL_SCIENCE,
    MECHANICAL_ENGINEERING,
    NUCLEAR_ENGINEERING,
    BUSINESS,
    APPLIED_LANGUAGE,
    ECONOMICS,
    INTERNATIONAL_AFFAIRS,
    MODERN_LANGUAGES,
    HTS,
    LMC,
    PUBLIC_POLICY,
    MATHEMATICS,
    PHYSICS,
    BIOCHEMISTRY,
    BIOLOGY,
    CHEMISTRY,
    DISCRETE_MATHEMATICS,
    EARTH_SCIENCE,
    PSYCHOLOGY
//    COMPUTER_SCIENCE,
//    COMPUTATIONAL_MEDIA,
//    CHEMISTRY,
//    PHYSICS,
//    ENGINEERING

}
